### ISSUE TITLE
CloudWatchAgent on Windows fails with "imds retry client will retry 1 times"

### ISSUE THREAD

**Issue by YoungLee9853** [aws/amazon-cloudwatch-agent#871] opened 2023-09-29 01:15 UTC
**Describe the bug**
In EC2 UserData, I am trying to execute "& 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a fetch-config -m ec2 -s -c file:C:\tmp\cloud-watch-agent-config.json" to install the cloud watch agent configuration on Windows Server 2022 host on start up. The UserData fails with "PS>TerminatingError(config-downloader.exe): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 2023/09/29 01:07:56 I! imds retry client will retry 1 times" message.

**Steps to reproduce**
1. Launch new Windows Server EC2 host with UserData including "& 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a fetch-config -m ec2 -s -c file:C:\tmp\cloud-watch-agent-config.json""
2. Wait for the user data script to fail...
  * To see the exact failure message, you will need to trap the exception and keep the transcript.

**What did you expect to see?**
AmazonCloudWatchAgent boots up with the provided configuration.

**What did you see instead?**
User data script fails.

**What version did you use?**
Version: (e.g., `v1.247350.0`, etc)

**What config did you use?**
Config: (e.g. the agent json config file)

**Environment**
Windows Server 2022

**Additional context**

**Comment by YoungLee9853** [comment] 2023-09-29 01:33
Looking at previous issues, it seems like the issue is related to https://github.com/aws/amazon-cloudwatch-agent/pull/516 .

**Comment by sethAmazon** [comment] 2023-09-29 17:45
Can you post your ami. We have tests for win-2022 where the agent does start.

**Comment by AllanBenson001** [comment] 2023-10-02 12:05
Same here. This worked last week.

AMI ID - ami-00c896faf296575ab

```
$config = @"
{
    "logs": {
        "logs_collected": {
            "windows_events": {
                "collect_list": [
                    {
                        "event_format": "xml",
                        "event_levels": [
                            "VERBOSE",
                            "INFORMATION",
                            "WARNING",
                            "ERROR",
                            "CRITICAL"
                        ],
                        "event_name": "Application",
                        "log_group_name": "/my/logs",
                        "log_stream_name": "{instance_id}/event-logs/application"
                    }
                ]
            }
        }
    }
}
"@

$installDirectory = "c:\temp\cw"
$downloadDirectory = $installDirectory 
$logsDirectory = $installDirectory 
    
New-Item -ItemType "directory" -Path $installDirectory

Set-Location -Path $installDirectory

$config | Set-Content -Path "$installDirectory/config.json"

Write-host "Installing Cloudwatch Agent"
$cwAgentInstaller = "$downloadDirectory\amazon-cloudwatch-agent.msi"
$cwAgentInstallPath = "C:\Program Files\Amazon\AmazonCloudWatchAgent"
Invoke-WebRequest "https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi" -OutFile $cwAgentInstaller
Start-Process -FilePath msiexec -Args "/i $cwAgentInstaller /l*v $logsDirectory\installCWAgentLog.log /qn" -Verb RunAs -Wait

Write-host "Load config"
& "$cwAgentInstallPath\amazon-cloudwatch-agent-ctl.ps1" -a fetch-config -m ec2 -s -c file:"$installDirectory/config.json"
```
Output:
```
Load config
****** processing amazon-cloudwatch-agent ******
I! Trying to detect region from ec2
config-downloader.exe : 2023/10/02 11:52:44 I! imds retry client will retry 1 times
At C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1:304 char:9
+         & $CWAProgramFiles\config-downloader.exe --output-dir "${JSON ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2023/10/02 11:5...l retry 1 times:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by 4wuyan** [comment] 2023-10-03 03:52
I am also seeing the same.

I noticed:
1. `C:\'Program Files'\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c file:\temp\cloudwatch-agent-config.json` works fine when I later connect to the EC2 and run this command manually. But it will fail when running as a part of user data.
2. It only starts to happen this week. More precisely, 02 Oct 2023. The same AMI that used to be fine last week is not ok this week. When I inspect the good EC2 from last week, I find the cloudwatch agent downloaded from https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi in my user data script is a different version.

Last week, https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi returns `Amazon CloudWatch Agent 1.300026.3 (2023-08-21)`, while this week, it's `Amazon CloudWatch Agent 1.300028.1 (2023-09-18)`. Hence, I suspect it's an issue related to the latest version(s) of cloudwatch agent.


```
PS C:\Program Files\Amazon\AmazonCloudWatchAgent> cat .\RELEASE_NOTES -head 20
========================================================================
Amazon CloudWatch Agent 1.300026.3 (2023-08-21)
========================================================================

Bug fixes:
* Fix credential chain for new components
* Fix metric renaming for Windows Performance Counters
* Fix log stream name translation for EMF on ECS
* Reduce RPM installation time

========================================================================
Amazon CloudWatch Agent 1.300026.2 (2023-08-10)
========================================================================

Bug fixes:
* Fix EMF log corruption when multiple clients are sending concurrently
* Drop invalid EMF logs
* Allow environment variables in OTEL config
* Revert credential chain when running as a service to prioritize instance role
```

```
PS C:\Windows\system32> cat 'C:\Program Files\Amazon\AmazonCloudWatchAgent\RELEASE_NOTES' -head 20
========================================================================
Amazon CloudWatch Agent 1.300028.1 (2023-09-18)
========================================================================

Bug fixes:
* Fix windows event logs to start only once

========================================================================
Amazon CloudWatch Agent 1.300028.0 (2023-09-11)
========================================================================

Bug fixes:
* Fix file pattern matching to support glob wildcard characters (!{})
* Use LogStreamName instead of ServiceName in token replacement for Prometheus
* Add fallback shared config files for credential ordering to maintain previous AWS SDK behavior
* Drop unsupported NaN, Inf, and out of range values

Enhancements:
* Try using IMDSv2 only first before using client with fallback
* Add support for configurable IMDS retries in the common-config.toml
```

References:
* https://github.com/aws/amazon-cloudwatch-agent/blob/main/RELEASE_NOTES

**Comment by ryanwilliams83** [comment] 2023-10-03 16:48
I put this together to demonstrate the problem and assist with troubleshooting.

https://github.com/ryanwilliams83/CloudWatchAgent-871
![image](https://github.com/aws/amazon-cloudwatch-agent/assets/3871256/317ad9c2-c6bb-4777-a931-478a88c50e0d)
![image](https://github.com/aws/amazon-cloudwatch-agent/assets/3871256/c7d91e65-8a1b-40fc-8ff0-082f81bd4aa2)
![image](https://github.com/aws/amazon-cloudwatch-agent/assets/3871256/bdbd5c8e-53ef-4032-a181-d42fe1e4ed05)

**Comment by sethAmazon** [comment] 2023-10-03 19:07
@AllanBenson001

Is this issue only when running this command in user data or when running in powershell. I ran this command in powershell after agent started and it worked. I want to make this issue only happens when starting with user data.

**Comment by sethAmazon** [comment] 2023-10-03 20:55
Okay so I was able to reproduce and fix the issue. Can you please take this version of the agent until we finish the patch release.

**Comment by sethAmazon** [comment] 2023-10-03 21:01
wget https://cloudwatch-agent-integration-bucket.s3.us-west-2.amazonaws.com/integration-test/packaging/98f45c9376c43f03d4968ee57d1b464b884f2303/amazon-cloudwatch-agent.msi

**Comment by AllanBenson001** [comment] 2023-10-04 09:45
> wget https://cloudwatch-agent-integration-bucket.s3.us-west-2.amazonaws.com/integration-test/packaging/98f45c9376c43f03d4968ee57d1b464b884f2303/amazon-cloudwatch-agent.msi

This fixes the issue. Thanks

**Comment by okankoAMZ** [comment] 2023-10-04 15:19
Closing the issue since root cause is found, the issue is mitigated.

**Closed by okankoAMZ** 2023-10-04 15:19 UTC
Labels: os/windows

**Comment by AllanBenson001** [comment] 2023-10-11 11:05
When will this fix be released so that I can start using the latest version again?

**Comment by ymtaye** [comment] 2023-10-11 12:49
The fix has been released and is included in the latest agent, can you please try using latest agent?
s3://amazon-cloud-watch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm

**Comment by ymtaye** [comment] 2023-10-11 14:10
The fix for this issue is currently released in the latest CloudWatch Agent, please try retrieving it by using the link below. Thanks!
https://amazoncloudwatch-agent.s3.amazonaws.com/windows/amd64/latest/amazon-cloudwatch-agent.msi
